<%-- /admin/content/reports_content.jsp --%>
<%-- This file contains only the content specific to the Reports page --%>

<h2 class="mb-3 border-bottom pb-2 text-body"><i class="fas fa-file-alt"></i> View Reports</h2>

<a href="${pageContext.request.contextPath}/admin/dashboard?action=generateReport" class="btn btn-primary mb-3 btn-add"><i class="fas fa-cogs"></i> Generate Monthly Report</a>

<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle">
        <thead class="table-light">
           <tr>
               <th>Report ID</th>
               <th>Report Type</th>
               <th>Generated Date</th>
               <th>Generated By</th>
               <th>Actions</th>
           </tr>
       </thead>
        <tbody>
        <c:forEach var="report" items="${reports}">
            <tr>
                <td>${report.id}</td>
                <td>${report.reportType}</td>
                <td><fmt:formatDate value="${report.generatedDate}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
                <td>${report.generatedById.username}</td>
                 <td>
                    <button class="btn btn-sm btn-success action-btn" onclick="viewReport('${report.details}')" title="View Details"><i class="fas fa-eye"></i></button>
                    <a href="${pageContext.request.contextPath}/admin/reports?action=delete&id=${report.id}" class="btn btn-sm btn-danger action-btn" title="Delete" onclick="return confirm('Are you sure you want to delete this report?');"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
             </tbody>
    </table>
</div>
