<%-- /admin/admin_reports.jsp --%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="Model.Staff" %> <%-- Import Staff model --%>
<%@ page import="Model.Reports" %> <%-- Import Reports model --%>
<%@ page import="java.util.List" %> <%-- Import List --%>
<%@ page import="java.text.SimpleDateFormat" %> <%-- For date formatting --%>

<%
    // --- Security Check: Redirect to login if not logged in ---
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff"); // Adjust attribute name if needed
    if (loggedInStaff == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp"); // Redirect to your login page
        return; // Stop processing the rest of the page
    }
    // Optional: Add role-specific check here if needed for viewing reports

    // --- TODO: Fetch report list data from backend ---
    // Example: List<Reports> reportList = reportDAO.getAllReports();
    List<?> reportList = List.of("Report1", "Report2"); // Placeholder - Replace with actual data list

    SimpleDateFormat dateTimeFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    // Set active page for sidebar highlighting
    request.setAttribute("activeAdminPage", "reports");
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Reports</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/styles/pages/body.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/styles/components/navbar.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/styles/components/footer.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/styles/pages/admin/admin_dashboard.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/styles/pages/admin/admin_sidebar.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <jsp:include page="/WEB-INF/views/components/navbar.jsp" />

    <div class="admin-container">
        <jsp:include page="/WEB-INF/views/admin/admin_sidebar.jsp" />

        <div class="admin-content">
            <h2><i class="fas fa-file-alt"></i> View Reports</h2>
            <hr>

            <%-- TODO: Add form or link to generate new reports --%>
            <a href="${pageContext.request.contextPath}/admin/reports/generate" class="btn-add"><i class="fas fa-cogs"></i> Generate Report</a>


            <div class="admin-table-container">
                <table class="admin-table">
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Report Type</th>
                            <th>Generated Date</th>
                            <th>Generated By</th> <%-- Need to fetch staff info --%>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%-- === TODO: Replace placeholders with loop for actual reportList === --%>
                        <%-- Example loop structure:
                        <% if (reportList == null || reportList.isEmpty()) { %>
                            <tr><td colspan="5">No reports found.</td></tr>
                        <% } else { %>
                            <% for (Reports report : reportList) { %>
                                <%-- String generatedBy = report.getGeneratedById() != null ? report.getGeneratedById().getUsername() : "System"; --%>
                                <tr>
                                    <td><%= report.getId() %></td>
                                    <td><%= report.getReportType() %></td>
                                    <td><%= dateTimeFormat.format(report.getGeneratedDate()) %></td>
                                    <td>Generated By Placeholder</td> <%-- Replace with actual generator --%>
                                    <td>
                                        <a href="${pageContext.request.contextPath}/admin/reports/view?id=<%= report.getId() %>" class="action-btn btn-view"><i class="fas fa-eye"></i> View Details</a>
                                        <%-- Maybe add download or delete actions --%>
                                        <a href="${pageContext.request.contextPath}/admin/reports/delete?id=<%= report.getId() %>" class="action-btn btn-delete" onclick="return confirm('Are you sure you want to delete report #<%= report.getId() %>?');"><i class="fas fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                            <% } %>
                        <% } %>
                        --%>

                         <%-- Placeholder Rows (Remove when using loop) --%>
                         <tr>
                             <td>1</td>
                             <td>Monthly Sales Summary</td>
                             <td>2025-04-01 08:00:00</td>
                             <td>GiantREX</td>
                              <td>
                                 <a href="#" class="action-btn btn-view"><i class="fas fa-eye"></i> View Details</a>
                                 <a href="#" class="action-btn btn-delete" onclick="return confirm('Are you sure?');"><i class="fas fa-trash"></i> Delete</a>
                             </td>
                         </tr>
                          <tr>
                             <td>2</td>
                             <td>User Activity Report</td>
                             <td>2025-04-20 14:00:00</td>
                             <td>staffREX</td>
                              <td>
                                 <a href="#" class="action-btn btn-view"><i class="fas fa-eye"></i> View Details</a>
                                 <a href="#" class="action-btn btn-delete" onclick="return confirm('Are you sure?');"><i class="fas fa-trash"></i> Delete</a>
                             </td>
                         </tr>
                         <%-- === End Placeholder Rows === --%>
                    </tbody>
                </table>
            </div>

            </div>
    </div>

    <jsp:include page="/WEB-INF/views/components/footer.jsp" />

</body>
</html>
